before_install:
- gem install compass
- npm install -g bower
- npm install -g grunt-cli
- npm install -g protractor
install:
- npm install -d
- bower install
- webdriver-manager update
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: XNGijrA8aJI4BYcNGgWY1+337H8OosFOaV/QFSO27ZiPAM2hEM6IL1tgL+kHNCepiOwfTdpwpLKgDBV8uwu0FIIF1k0La8pJ32XCJw6WENZ4iwUiuEsCgiZIC4TJENFqlELxK+9RLb6lr9XcqnFLlBm21h78oU6iocp7RCIQZWs=
  - secure: MncVLRH0Res38Hir8UbRqu1p3Frcp/sltXEPCsAoX+XYKM1gA/j+zoYfxLXyWB/3EkUX6J+rlCzGK59lEbygjP66AnqImJ5xds7lW5LLfrHlGFxOe1+Lsp9Z7FMT+Q64bloNqq87sC2uoqVLdBlU+kKYF25zvFEoOQohiwyqWN0=
