before_install:
- gem install compass
- npm install -g bower
- npm install -g grunt-cli
- npm install -g protractor
install:
- npm install -d
- bower install
- webdriver-manager update
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
language: node_js
node_js:
- '0.10'
